version: '3.8'

services:
  nestjs-app:
    image: nest-api
    container_name: nestjs-app
    build:
      dockerfile: dockerfile
      context: .
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=oneprediction
      - DATABASE_NAME=oneprediction
      - MODE=DEV
      - RUN_MIGRATIONS=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_DB=oneprediction
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=oneprediction
    ports:
      - '5432:5432'

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
